[package]
name = "backend"
version = "0.1.0"
authors = ["ScipioAfricanus1 <bdharris3@uh.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yahoo-finance="0.3.0"
serde_json="1.0"
actix-web="3"